POST http://localhost:8000/api/post/4/link
Accept: application/json
Content-Type: application/json;
Authorization: Bearer 1|Xx7EsxzUWdwoiO3E8LE5AUa14DGYCWhml5PaNJI7dd23c8bc

{
    "name": "Que tal?",
    "dead_line": "2023/12/12",
    "description": "Hola ue tal estan ustedes",
    "group_id": 1,
    "content": "Adios?",
    "public": "1",
    "links": [
        {
            "link": "https://youtu.be/u6h2ZACBgko?si=yk91514kaEhwLHVK",
            "link_name": "yt"
        },
        {
            "link": "https://github.com/ramon2533",
            "link_name": "mi github3"
        }
    ]
}
###


GET http://localhost:8000/api/post/4
Content-Type: application/json
Authorization: 1|fhnGZT1Uk4L4SgCMiWe6JJVdJjaBwlhSJ4dKmB4Wec2a9ef8

###
POST http://localhost:8000/api/user
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|Xx7EsxzUWdwoiO3E8LE5AUa14DGYCWhml5PaNJI7dd23c8bc

{
    "join_code" : "tHF9ftw1FyD9vDCsF1cuzMTQuO9QzAFJhvBb5e53efU7j3Msq8",
    "name" : "ramon",
    "email" : "abichiela@gmmail",
    "password" : "123456789.",
    "password_confirmation" : "123456789.",
    "full_name" : "jose ramon",
    "surname" : "galazc",
    "birth_date" : "2003/04/12",
    "level" : "C1"
}


###
POST http://localhost:8000/api/group/9/post
Accept: application/json
Authorization: 1|KNXyOQxNlGEnRT1Qmp2FMUDevIBrcVYndcvnPFjk4ba08cc2
Content-Type: multipart/form-data; boundary=boundary
User-Agent: IntelliJ HTTP Client/PhpStorm 2024.1.1 RC
Accept-Encoding: br, deflate, gzip, x-gzip
Cookie: authToken=5%257CUeYnJAyJYdiP6n5pnZjGdgl8oUgSaYjO9drKcE086c39ad2b
content-length: 792

--boundary
Content-Disposition: form-data; name="files[1]"; filename="input.txt"
Content-Type: text/plain

Hola
--boundary
Content-Disposition: form-data; name="files[2]"; filename="irene.jpeg"
Content-Type: image/jpg

< C:\Users\pcram\Downloads\05-IRENEPINILLANIETO.jpg
--boundary
Content-Disposition: form-data; name="subject"

2024/12/12
--boundary
Content-Disposition: form-data; name="name"

Prueba3
--boundary
Content-Disposition: form-data; name="description"

     Hola ue tal estan ustedes
--boundary
Content-Disposition: form-data; name="dead_line"

2024/12/12
--boundary--
