DELETE http://localhost:8000/api/assignment/7
Accept: application/json
Content-Type: application/json;
Authorization: 1|KNXyOQxNlGEnRT1Qmp2FMUDevIBrcVYndcvnPFjk4ba08cc2

{
    "name": "Que tal?",
    "dead_line": "2023/12/12",
    "description": "Hola ue tal estan ustedes",
    "group_id": 1
}
###


GET http://localhost:8000/api/assignment/7
Accept: application/json
Content-Type: application/json
Authorization: 1|fhnGZT1Uk4L4SgCMiWe6JJVdJjaBwlhSJ4dKmB4Wec2a9ef8

###
POST http://localhost:8000/api/login-token
Content-Type: application/json
Accept: application/json

{
    "name" : "gerunio",
    "email" : "abichiela@gmail",
    "password" : "123456789",
    "password_confirmation" : "123456789"
}
